# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Combine-UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Combine-UIKit
  pod 'CombineCocoa'
  pod 'Kingfisher', '~> 5.0'
end
